return {
    Accent = Color3.fromRGB(102, 136, 204), -- #6688cc

    AcrylicMain = Color3.fromRGB(0, 12, 24), -- #000c18
    AcrylicBorder = Color3.fromRGB(43, 43, 74), -- #2b2b4a
    AcrylicGradient = ColorSequence.new(Color3.fromRGB(0, 12, 24), Color3.fromRGB(0, 12, 24)),
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromRGB(43, 43, 74), -- #2b2b4a
    Tab = Color3.fromRGB(128, 162, 194), -- #80a2c2

    Element = Color3.fromRGB(24, 31, 47), -- #181f2f
    ElementBorder = Color3.fromRGB(43, 43, 74), -- #2b2b4a
    InElementBorder = Color3.fromRGB(0, 99, 165), -- #0063a5
    ElementTransparency = 0,

    ToggleSlider = Color3.fromRGB(0, 99, 165), -- #0063a5
    ToggleToggled = Color3.fromRGB(24, 31, 47), -- #181f2f

    SliderRail = Color3.fromRGB(0, 99, 165), -- #0063a5

    DropdownFrame = Color3.fromRGB(24, 31, 47), -- #181f2f
    DropdownHolder = Color3.fromRGB(24, 31, 47), -- #181f2f
    DropdownBorder = Color3.fromRGB(43, 43, 74), -- #2b2b4a
    DropdownOption = Color3.fromRGB(102, 136, 204), -- #6688cc

    Keybind = Color3.fromRGB(24, 31, 47), -- #181f2f

    Input = Color3.fromRGB(24, 31, 47), -- #181f2f
    InputFocused = Color3.fromRGB(24, 31, 47), -- #181f2f
    InputIndicator = Color3.fromRGB(64, 99, 133), -- #406385

    Dialog = Color3.fromRGB(38, 38, 65), -- #262641
    DialogHolder = Color3.fromRGB(6, 6, 33), -- #060621
    DialogHolderLine = Color3.fromRGB(43, 43, 74), -- #2b2b4a
    DialogButton = Color3.fromRGB(24, 31, 47), -- #181f2f
    DialogButtonBorder = Color3.fromRGB(43, 43, 74), -- #2b2b4a
    DialogBorder = Color3.fromRGB(43, 43, 74), -- #2b2b4a
    DialogInput = Color3.fromRGB(24, 31, 47), -- #181f2f
    DialogInputLine = Color3.fromRGB(0, 99, 165), -- #0063a5

    Text = Color3.fromRGB(102, 136, 204), -- #6688cc
    SubText = Color3.fromRGB(64, 99, 133), -- #406385
    Hover = Color3.fromRGB(8, 40, 107), -- #08286b
    HoverChange = 0.1
}