return {
    Accent = Color3.fromHex("#ec6a3f"),

    AcrylicMain = Color3.fromHex("#31312e"),
    AcrylicBorder = Color3.fromHex("#403f3a"),
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#31312e"), Color3.fromHex("#31312e")),
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromHex("#403f3a"),
    Tab = Color3.fromHex("#dddddd"),

    Element = Color3.fromHex("#373633"),
    ElementBorder = Color3.fromHex("#403f3a"),
    InElementBorder = Color3.fromHex("#ec6a3f"),
    ElementTransparency = 0,

    ToggleSlider = Color3.fromHex("#ec6a3f"),
    ToggleToggled = Color3.fromHex("#31312e"),

    SliderRail = Color3.fromHex("#ec6a3f"),

    DropdownFrame = Color3.fromHex("#373633"),
    DropdownHolder = Color3.fromHex("#373633"),
    DropdownBorder = Color3.fromHex("#403f3a"),
    DropdownOption = Color3.fromHex("#dddddd"),

    Keybind = Color3.fromHex("#373633"),

    Input = Color3.fromHex("#373633"),
    InputFocused = Color3.fromHex("#373633"),
    InputIndicator = Color3.fromHex("#747c84"),

    Dialog = Color3.fromHex("#3c3b37"),
    DialogHolder = Color3.fromHex("#31312e"),
    DialogHolderLine = Color3.fromHex("#403f3a"),
    DialogButton = Color3.fromHex("#373633"),
    DialogButtonBorder = Color3.fromHex("#403f3a"),
    DialogBorder = Color3.fromHex("#403f3a"),
    DialogInput = Color3.fromHex("#373633"),
    DialogInputLine = Color3.fromHex("#ec6a3f"),

    Text = Color3.fromHex("#dddddd"),
    SubText = Color3.fromHex("#747c84"),
    Hover = Color3.fromHex("#403f3a"),
    HoverChange = 0.1
}