return {
    Accent = Color3.fromHex("#00BCD4"),

    AcrylicMain = Color3.fromHex("#29353b"),
    AcrylicBorder = Color3.fromHex("#222D32"),
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#29353b"), Color3.fromHex("#29353b")),
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromHex("#222D32"),
    Tab = Color3.fromHex("#EEFFFF"),

    Element = Color3.fromHex("#243035"),
    ElementBorder = Color3.fromHex("#222D32"),
    InElementBorder = Color3.fromHex("#00BCD4"),
    ElementTransparency = 0,

    ToggleSlider = Color3.fromHex("#00BCD4"),
    ToggleToggled = Color3.fromHex("#29353b"),

    SliderRail = Color3.fromHex("#00BCD4"),

    DropdownFrame = Color3.fromHex("#243035"),
    DropdownHolder = Color3.fromHex("#243035"),
    DropdownBorder = Color3.fromHex("#222D32"),
    DropdownOption = Color3.fromHex("#EEFFFF"),

    Keybind = Color3.fromHex("#243035"),

    Input = Color3.fromHex("#243035"),
    InputFocused = Color3.fromHex("#243035"),
    InputIndicator = Color3.fromHex("#546E7A"),

    Dialog = Color3.fromHex("#222D32"),
    DialogHolder = Color3.fromHex("#29353b"),
    DialogHolderLine = Color3.fromHex("#222D32"),
    DialogButton = Color3.fromHex("#243035"),
    DialogButtonBorder = Color3.fromHex("#222D32"),
    DialogBorder = Color3.fromHex("#222D32"),
    DialogInput = Color3.fromHex("#243035"),
    DialogInputLine = Color3.fromHex("#00BCD4"),

    Text = Color3.fromHex("#EEFFFF"),
    SubText = Color3.fromHex("#546E7A"),
    Hover = Color3.fromHex("#2D3B42"),
    HoverChange = 0.1
}