return {
    Accent = Color3.fromHex("#b133ff"),

    AcrylicMain = Color3.fromHex("#120024"),
    AcrylicBorder = Color3.fromHex("#4d057b"),
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#120024"), Color3.fromHex("#120024")),
    AcrylicNoise = 0.92,

    TitleBarLine = Color3.fromHex("#4d057b"),
    Tab = Color3.fromHex("#e9d9f2"),

    Element = Color3.fromHex("#25013c"),
    ElementBorder = Color3.fromHex("#4d057b"),
    InElementBorder = Color3.fromHex("#b133ff"),
    ElementTransparency = 0.85,

    ToggleSlider = Color3.fromHex("#7d16bf"),
    ToggleToggled = Color3.fromHex("#120024"),

    SliderRail = Color3.fromHex("#7d16bf"),

    DropdownFrame = Color3.fromHex("#25013c"),
    DropdownHolder = Color3.fromHex("#25013c"),
    DropdownBorder = Color3.fromHex("#4d057b"),
    DropdownOption = Color3.fromHex("#e9d9f2"),

    Keybind = Color3.fromHex("#25013c"),

    Input = Color3.fromHex("#180030"),
    InputFocused = Color3.fromHex("#180030"),
    InputIndicator = Color3.fromHex("#9e85ad"),

    Dialog = Color3.fromHex("#25013c"),
    DialogHolder = Color3.fromHex("#120024"),
    DialogHolderLine = Color3.fromHex("#4d057b"),
    DialogButton = Color3.fromHex("#25013c"),
    DialogButtonBorder = Color3.fromHex("#4d057b"),
    DialogBorder = Color3.fromHex("#4d057b"),
    DialogInput = Color3.fromHex("#180030"),
    DialogInputLine = Color3.fromHex("#b133ff"),

    Text = Color3.fromHex("#e9d9f2"),
    SubText = Color3.fromHex("#9e85ad"),
    Hover = Color3.fromHex("#4d057b"),
    HoverChange = 0.1
}