return {
    Accent = Color3.fromHex("#5294e2"),

    AcrylicMain = Color3.fromHex("#383c4a"),
    AcrylicBorder = Color3.fromHex("#404f7d"),
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#383c4a"), Color3.fromHex("#383c4a")),
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromHex("#404f7d"),
    Tab = Color3.fromHex("#a2a2a2"),

    Element = Color3.fromHex("#4b5162"),
    ElementBorder = Color3.fromHex("#404f7d"),
    InElementBorder = Color3.fromHex("#5294e2"),
    ElementTransparency = 0,

    ToggleSlider = Color3.fromHex("#5294e2"),
    ToggleToggled = Color3.fromHex("#383c4a"),

    SliderRail = Color3.fromHex("#5294e2"),

    DropdownFrame = Color3.fromHex("#4b5162"),
    DropdownHolder = Color3.fromHex("#4b5162"),
    DropdownBorder = Color3.fromHex("#404f7d"),
    DropdownOption = Color3.fromHex("#a2a2a2"),

    Keybind = Color3.fromHex("#4b5162"),

    Input = Color3.fromHex("#4b5162"),
    InputFocused = Color3.fromHex("#4b5162"),
    InputIndicator = Color3.fromHex("#7285b7"),

    Dialog = Color3.fromHex("#434858"),
    DialogHolder = Color3.fromHex("#383c4a"),
    DialogHolderLine = Color3.fromHex("#404f7d"),
    DialogButton = Color3.fromHex("#4b5162"),
    DialogButtonBorder = Color3.fromHex("#404f7d"),
    DialogBorder = Color3.fromHex("#404f7d"),
    DialogInput = Color3.fromHex("#4b5162"),
    DialogInputLine = Color3.fromHex("#5294e2"),

    Text = Color3.fromHex("#a2a2a2"),
    SubText = Color3.fromHex("#7285b7"),
    Hover = Color3.fromHex("#4b5162"),
    HoverChange = 0.1
}