return {
    Accent = Color3.fromRGB(109, 180, 120),

    AcrylicMain = Color3.fromRGB(38, 38, 38),
    AcrylicBorder = Color3.fromRGB(85, 85, 85),
    AcrylicGradient = ColorSequence.new(Color3.fromRGB(38, 38, 38), Color3.fromRGB(38, 38, 38)),
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromRGB(189, 189, 189),
    Tab = Color3.fromRGB(109, 180, 120),

    Element = Color3.fromRGB(42, 42, 42),
    ElementBorder = Color3.fromRGB(51, 51, 51),
    InElementBorder = Color3.fromRGB(51, 51, 51),
    ElementTransparency = 0,

    ToggleSlider = Color3.fromRGB(103, 169, 113),
    ToggleToggled = Color3.fromRGB(255, 255, 255),

    SliderRail = Color3.fromRGB(51, 51, 51),

    DropdownFrame = Color3.fromRGB(68, 68, 68),
    DropdownHolder = Color3.fromRGB(68, 68, 68),
    DropdownBorder = Color3.fromRGB(38, 38, 38),
    DropdownOption = Color3.fromRGB(153, 200, 255),

    Keybind = Color3.fromRGB(54, 54, 54),

    Input = Color3.fromRGB(27, 27, 27),
    InputFocused = Color3.fromRGB(51, 51, 51),
    InputIndicator = Color3.fromRGB(197, 184, 161),

    Dialog = Color3.fromRGB(38, 38, 38),
    DialogHolder = Color3.fromRGB(58, 52, 46),
    DialogHolderLine = Color3.fromRGB(40, 40, 40),
    DialogButton = Color3.fromRGB(42, 42, 42),
    DialogButtonBorder = Color3.fromRGB(51, 51, 51),
    DialogBorder = Color3.fromRGB(189, 189, 189),
    DialogInput = Color3.fromRGB(27, 27, 27),
    DialogInputLine = Color3.fromRGB(197, 184, 161),

    Text = Color3.fromRGB(197, 184, 161),
    SubText = Color3.fromRGB(158, 158, 158),
    Hover = Color3.fromRGB(149, 149, 149),
    HoverChange = 0.04
}