return {
    Accent = Color3.fromHex("#34FEBB"),

    AcrylicMain = Color3.fromHex("#1D262F"),
    AcrylicBorder = Color3.fromHex("#303F4F"),
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#1D262F"), Color3.fromHex("#1D262F")),
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromHex("#303F4F"),
    Tab = Color3.fromHex("#88b4e7"),

    Element = Color3.fromHex("#232D38"),
    ElementBorder = Color3.fromHex("#303F4F"),
    InElementBorder = Color3.fromHex("#34FEBB"),
    ElementTransparency = 0,

    ToggleSlider = Color3.fromHex("#34FEBB"),
    ToggleToggled = Color3.fromHex("#1D262F"),

    SliderRail = Color3.fromHex("#34FEBB"),

    DropdownFrame = Color3.fromHex("#232D38"),
    DropdownHolder = Color3.fromHex("#232D38"),
    DropdownBorder = Color3.fromHex("#303F4F"),
    DropdownOption = Color3.fromHex("#88b4e7"),

    Keybind = Color3.fromHex("#232D38"),

    Input = Color3.fromHex("#232D38"),
    InputFocused = Color3.fromHex("#232D38"),
    InputIndicator = Color3.fromHex("#444c55"),

    Dialog = Color3.fromHex("#232D38"),
    DialogHolder = Color3.fromHex("#1D262F"),
    DialogHolderLine = Color3.fromHex("#303F4F"),
    DialogButton = Color3.fromHex("#232D38"),
    DialogButtonBorder = Color3.fromHex("#303F4F"),
    DialogBorder = Color3.fromHex("#303F4F"),
    DialogInput = Color3.fromHex("#232D38"),
    DialogInputLine = Color3.fromHex("#34FEBB"),

    Text = Color3.fromHex("#88b4e7"),
    SubText = Color3.fromHex("#444c55"),
    Hover = Color3.fromHex("#354454"),
    HoverChange = 0.1
}