return {
    Accent = Color3.fromHex("#fe7734"),

    AcrylicMain = Color3.fromHex("#24242e"),
    AcrylicBorder = Color3.fromHex("#3a3a4a"),
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#24242e"), Color3.fromHex("#24242e")),
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromHex("#3a3a4a"),
    Tab = Color3.fromHex("#8686cb"),

    Element = Color3.fromHex("#2B2B36"),
    ElementBorder = Color3.fromHex("#3a3a4a"),
    InElementBorder = Color3.fromHex("#fe7734"),
    ElementTransparency = 0,

    ToggleSlider = Color3.fromHex("#fe7734"),
    ToggleToggled = Color3.fromHex("#24242e"),

    SliderRail = Color3.fromHex("#fe7734"),

    DropdownFrame = Color3.fromHex("#2B2B36"),
    DropdownHolder = Color3.fromHex("#2B2B36"),
    DropdownBorder = Color3.fromHex("#3a3a4a"),
    DropdownOption = Color3.fromHex("#8686cb"),

    Keybind = Color3.fromHex("#2B2B36"),

    Input = Color3.fromHex("#2B2B36"),
    InputFocused = Color3.fromHex("#2B2B36"),
    InputIndicator = Color3.fromHex("#49495a"),

    Dialog = Color3.fromHex("#2B2B36"),
    DialogHolder = Color3.fromHex("#24242e"),
    DialogHolderLine = Color3.fromHex("#3a3a4a"),
    DialogButton = Color3.fromHex("#2B2B36"),
    DialogButtonBorder = Color3.fromHex("#3a3a4a"),
    DialogBorder = Color3.fromHex("#3a3a4a"),
    DialogInput = Color3.fromHex("#2B2B36"),
    DialogInputLine = Color3.fromHex("#fe7734"),

    Text = Color3.fromHex("#8686cb"),
    SubText = Color3.fromHex("#49495a"),
    Hover = Color3.fromHex("#3F3F4F"),
    HoverChange = 0.1
}