return {
    Accent = Color3.fromHex("#fecb52"),

    AcrylicMain = Color3.fromHex("#2c2826"),
    AcrylicBorder = Color3.fromHex("#48413d"),
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#2c2826"), Color3.fromHex("#2c2826")),
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromHex("#48413d"),
    Tab = Color3.fromHex("#bd987f"),

    Element = Color3.fromHex("#35302D"),
    ElementBorder = Color3.fromHex("#48413d"),
    InElementBorder = Color3.fromHex("#fecb52"),
    ElementTransparency = 0,

    ToggleSlider = Color3.fromHex("#fecb52"),
    ToggleToggled = Color3.fromHex("#2c2826"),

    SliderRail = Color3.fromHex("#fecb52"),

    DropdownFrame = Color3.fromHex("#35302D"),
    DropdownHolder = Color3.fromHex("#35302D"),
    DropdownBorder = Color3.fromHex("#48413d"),
    DropdownOption = Color3.fromHex("#bd987f"),

    Keybind = Color3.fromHex("#35302D"),

    Input = Color3.fromHex("#35302D"),
    InputFocused = Color3.fromHex("#35302D"),
    InputIndicator = Color3.fromHex("#564b43"),

    Dialog = Color3.fromHex("#35302D"),
    DialogHolder = Color3.fromHex("#2c2826"),
    DialogHolderLine = Color3.fromHex("#48413d"),
    DialogButton = Color3.fromHex("#35302D"),
    DialogButtonBorder = Color3.fromHex("#48413d"),
    DialogBorder = Color3.fromHex("#48413d"),
    DialogInput = Color3.fromHex("#35302D"),
    DialogInputLine = Color3.fromHex("#fecb52"),

    Text = Color3.fromHex("#bd987f"),
    SubText = Color3.fromHex("#564b43"),
    Hover = Color3.fromHex("#4D4642"),
    HoverChange = 0.1
}