return {
    Accent = Color3.fromHex("#e7f98b"),

    AcrylicMain = Color3.fromHex("#2a2d2a"),
    AcrylicBorder = Color3.fromHex("#424842"),
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#2a2d2a"), Color3.fromHex("#2a2d2a")),
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromHex("#424842"),
    Tab = Color3.fromHex("#a9bca9"),

    Element = Color3.fromHex("#313531"),
    ElementBorder = Color3.fromHex("#424842"),
    InElementBorder = Color3.fromHex("#e7f98b"),
    ElementTransparency = 0,

    ToggleSlider = Color3.fromHex("#e7f98b"),
    ToggleToggled = Color3.fromHex("#2a2d2a"),

    SliderRail = Color3.fromHex("#e7f98b"),

    DropdownFrame = Color3.fromHex("#313531"),
    DropdownHolder = Color3.fromHex("#313531"),
    DropdownBorder = Color3.fromHex("#424842"),
    DropdownOption = Color3.fromHex("#a9bca9"),

    Keybind = Color3.fromHex("#313531"),

    Input = Color3.fromHex("#313531"),
    InputFocused = Color3.fromHex("#313531"),
    InputIndicator = Color3.fromHex("#585f58"),

    Dialog = Color3.fromHex("#313531"),
    DialogHolder = Color3.fromHex("#2a2d2a"),
    DialogHolderLine = Color3.fromHex("#424842"),
    DialogButton = Color3.fromHex("#313531"),
    DialogButtonBorder = Color3.fromHex("#424842"),
    DialogBorder = Color3.fromHex("#424842"),
    DialogInput = Color3.fromHex("#313531"),
    DialogInputLine = Color3.fromHex("#e7f98b"),

    Text = Color3.fromHex("#a9bca9"),
    SubText = Color3.fromHex("#585f58"),
    Hover = Color3.fromHex("#474D47"),
    HoverChange = 0.1
}