return {
    Accent = Color3.fromHex("#fec38f"),

    AcrylicMain = Color3.fromHex("#2c2734"),
    AcrylicBorder = Color3.fromHex("#443d51"),
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#2c2734"), Color3.fromHex("#2c2734")),
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromHex("#443d51"),
    Tab = Color3.fromHex("#cab2fa"),

    Element = Color3.fromHex("#342E3D"),
    ElementBorder = Color3.fromHex("#443d51"),
    InElementBorder = Color3.fromHex("#fec38f"),
    ElementTransparency = 0,

    ToggleSlider = Color3.fromHex("#fec38f"),
    ToggleToggled = Color3.fromHex("#2c2734"),

    SliderRail = Color3.fromHex("#fec38f"),

    DropdownFrame = Color3.fromHex("#342E3D"),
    DropdownHolder = Color3.fromHex("#342E3D"),
    DropdownBorder = Color3.fromHex("#443d51"),
    DropdownOption = Color3.fromHex("#cab2fa"),

    Keybind = Color3.fromHex("#342E3D"),

    Input = Color3.fromHex("#342E3D"),
    InputFocused = Color3.fromHex("#342E3D"),
    InputIndicator = Color3.fromHex("#544d60"),

    Dialog = Color3.fromHex("#342E3D"),
    DialogHolder = Color3.fromHex("#2c2734"),
    DialogHolderLine = Color3.fromHex("#443d51"),
    DialogButton = Color3.fromHex("#342E3D"),
    DialogButtonBorder = Color3.fromHex("#443d51"),
    DialogBorder = Color3.fromHex("#443d51"),
    DialogInput = Color3.fromHex("#342E3D"),
    DialogInputLine = Color3.fromHex("#fec38f"),

    Text = Color3.fromHex("#cab2fa"),
    SubText = Color3.fromHex("#544d60"),
    Hover = Color3.fromHex("#494256"),
    HoverChange = 0.1
}