return {
    Accent = Color3.fromHex("#cb5226"),

    AcrylicMain = Color3.fromHex("#eff0f1"),
    AcrylicBorder = Color3.fromHex("#e9d18d"),
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#eff0f1"), Color3.fromHex("#eff0f1")),
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromHex("#e9d18d"),
    Tab = Color3.fromHex("#5e5e5e"),

    Element = Color3.fromHex("#fdf6e3"),
    ElementBorder = Color3.fromHex("#e9d18d"),
    InElementBorder = Color3.fromHex("#cb5226"),
    ElementTransparency = 0,

    ToggleSlider = Color3.fromHex("#cb5226"),
    ToggleToggled = Color3.fromHex("#fdf6e3"),

    SliderRail = Color3.fromHex("#cb5226"),

    DropdownFrame = Color3.fromHex("#fbefce"),
    DropdownHolder = Color3.fromHex("#fbefce"),
    DropdownBorder = Color3.fromHex("#e9d18d"),
    DropdownOption = Color3.fromHex("#5e5e5e"),

    Keybind = Color3.fromHex("#fdf6e3"),

    Input = Color3.fromHex("#fdf6e3"),
    InputFocused = Color3.fromHex("#fdf6e3"),
    InputIndicator = Color3.fromHex("#93a1a1"),

    Dialog = Color3.fromHex("#fbefce"),
    DialogHolder = Color3.fromHex("#fbefce"),
    DialogHolderLine = Color3.fromHex("#e9d18d"),
    DialogButton = Color3.fromHex("#fbefce"),
    DialogButtonBorder = Color3.fromHex("#e9d18d"),
    DialogBorder = Color3.fromHex("#e9d18d"),
    DialogInput = Color3.fromHex("#fdf6e3"),
    DialogInputLine = Color3.fromHex("#cb5226"),

    Text = Color3.fromHex("#5e5e5e"),
    SubText = Color3.fromHex("#93a1a1"),
    Hover = Color3.fromHex("#d6d6d6"),
    HoverChange = 0.1
}