return {
    Accent = Color3.fromHex("#005cc5"), -- focusBorder

    AcrylicMain = Color3.fromHex("#1f2428"), -- sideBar.background
    AcrylicBorder = Color3.fromHex("#1b1f23"),  -- titleBar.border
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#1f2428"), Color3.fromHex("#1f2428")),-- sideBar.background
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromHex("#1b1f23"), -- titleBar.border
    Tab = Color3.fromHex("#e1e4e8"), -- titleBar.activeForeground

    Element = Color3.fromHex("#2f363d"),  -- input.background
    ElementBorder = Color3.fromHex("#1b1f23"), -- input.border
    InElementBorder = Color3.fromHex("#005cc5"), -- focusBorder
    ElementTransparency = 0,

    ToggleSlider = Color3.fromHex("#005cc5"), -- focusBorder
    ToggleToggled = Color3.fromHex("#2f363d"), -- input.background

    SliderRail = Color3.fromHex("#005cc5"),  -- focusBorder

    DropdownFrame = Color3.fromHex("#2f363d"), -- dropdown.background
    DropdownHolder = Color3.fromHex("#2f363d"), -- dropdown.background
    DropdownBorder = Color3.fromHex("#1b1f23"),  -- dropdown.border
    DropdownOption = Color3.fromHex("#e1e4e8"),  -- dropdown.foreground

    Keybind = Color3.fromHex("#2f363d"),  -- input.background

    Input = Color3.fromHex("#2f363d"),  -- input.background
    InputFocused = Color3.fromHex("#2f363d"),  -- input.background
    InputIndicator = Color3.fromHex("#959da5"),-- input.placeholderForeground

    Dialog = Color3.fromHex("#2f363d"),  -- notifications.background
    DialogHolder = Color3.fromHex("#2f363d"), -- notifications.background
    DialogHolderLine = Color3.fromHex("#444d56"), --  textBlockQuote.border
    DialogButton = Color3.fromHex("#2f363d"), --  Your preferred button background
    DialogButtonBorder = Color3.fromHex("#1b1f23"),-- Your preferred button border
    DialogBorder = Color3.fromHex("#1b1f23"), -- notifications.border
    DialogInput = Color3.fromHex("#2f363d"), -- notifications.background
    DialogInputLine = Color3.fromHex("#005cc5"), -- focusBorder

    Text = Color3.fromHex("#d1d5da"), -- foreground
    SubText = Color3.fromHex("#959da5"), -- descriptionForeground
    Hover = Color3.fromHex("#282e34"), -- list.hoverBackground
    HoverChange = 0.1
}