return {
    Accent = Color3.fromHex("#0969da"), -- focusBorder

    AcrylicMain = Color3.fromHex("#f6f8fa"), -- textBlockQuote.background
    AcrylicBorder = Color3.fromHex("#d0d7de"), -- textBlockQuote.border
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#f6f8fa"), Color3.fromHex("#f6f8fa")), -- textBlockQuote.background
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromHex("#d0d7de"), -- titleBar.border
    Tab = Color3.fromHex("#24292f"), -- foreground

    Element = Color3.fromHex("#ffffff"),  -- input.background
    ElementBorder = Color3.fromHex("#d0d7de"), -- input.border
    InElementBorder = Color3.fromHex("#0969da"), -- focusBorder
    ElementTransparency = 0,

    ToggleSlider = Color3.fromHex("#0969da"), -- focusBorder
    ToggleToggled = Color3.fromHex("#ffffff"), -- input.background

    SliderRail = Color3.fromHex("#0969da"), -- focusBorder

    DropdownFrame = Color3.fromHex("#ffffff"), -- dropdown.background
    DropdownHolder = Color3.fromHex("#ffffff"), -- dropdown.background
    DropdownBorder = Color3.fromHex("#d0d7de"), -- dropdown.border
    DropdownOption = Color3.fromHex("#24292f"), -- foreground

    Keybind = Color3.fromHex("#ffffff"), -- input.background

    Input = Color3.fromHex("#ffffff"), -- input.background
    InputFocused = Color3.fromHex("#ffffff"), -- input.background
    InputIndicator = Color3.fromHex("#6e7781"), -- input.placeholderForeground

    Dialog = Color3.fromHex("#ffffff"), -- notifications.background
    DialogHolder = Color3.fromHex("#ffffff"), -- notifications.background
    DialogHolderLine = Color3.fromHex("#d0d7de"),  -- notifications.border
    DialogButton = Color3.fromHex("#ffffff"), -- Your preferred button background
    DialogButtonBorder = Color3.fromHex("#20252c"), -- Your preferred button border
    DialogBorder = Color3.fromHex("#d0d7de"), -- notifications.border
    DialogInput = Color3.fromHex("#ffffff"),  -- notifications.background
    DialogInputLine = Color3.fromHex("#0969da"), -- focusBorder

    Text = Color3.fromHex("#24292f"),  -- foreground
    SubText = Color3.fromHex("#57606a"), -- descriptionForeground
    Hover = Color3.fromHex("#eaeef2"),  -- list.hoverBackground (alpha removed)
    HoverChange = 0.1
}