return {
    Accent = Color3.fromHex("2188ff"), -- focusBorder

    AcrylicMain = Color3.fromHex("f6f8fa"), -- sideBar.background
    AcrylicBorder = Color3.fromHex("e1e4e8"), -- titleBar.border
    AcrylicGradient = ColorSequence.new(Color3.fromHex("f6f8fa"), Color3.fromHex("f6f8fa")), -- sideBar.background
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromHex("e1e4e8"), -- titleBar.border
    Tab = Color3.fromHex("2f363d"), -- tab.activeForeground

    Element = Color3.fromHex("fafbfc"), -- input.background
    ElementBorder = Color3.fromHex("e1e4e8"), -- input.border
    InElementBorder = Color3.fromHex("2188ff"), -- focusBorder
    ElementTransparency = 0,

    ToggleSlider = Color3.fromHex("2188ff"), -- focusBorder
    ToggleToggled = Color3.fromHex("fafbfc"), -- input.background

    SliderRail = Color3.fromHex("2188ff"), -- focusBorder

    DropdownFrame = Color3.fromHex("fafbfc"), -- dropdown.background
    DropdownHolder = Color3.fromHex("fafbfc"), -- dropdown.background
    DropdownBorder = Color3.fromHex("e1e4e8"), -- dropdown.border
    DropdownOption = Color3.fromHex("2f363d"), -- dropdown.foreground

    Keybind = Color3.fromHex("fafbfc"), -- input.background

    Input = Color3.fromHex("fafbfc"), -- input.background
    InputFocused = Color3.fromHex("fafbfc"), -- input.background
    InputIndicator = Color3.fromHex("959da5"),  -- input.placeholderForeground

    Dialog = Color3.fromHex("fafbfc"), --  Using a light background for dialog
    DialogHolder = Color3.fromHex("fafbfc"), -- Using a light background for dialog holder
    DialogHolderLine = Color3.fromHex("e1e4e8"), --  Using a subtle line color
    DialogButton = Color3.fromHex("#fafbfc"),  -- Your preferred button background
    DialogButtonBorder = Color3.fromHex("#20252c"),  -- Your preferred button border
    DialogBorder = Color3.fromHex("e1e4e8"), -- dropdown.border
    DialogInput = Color3.fromHex("fafbfc"),  -- input.background
    DialogInputLine = Color3.fromHex("2188ff"), -- focusBorder

    Text = Color3.fromHex("24292e"), -- editor.foreground
    SubText = Color3.fromHex("6a737d"), -- descriptionForeground
    Hover = Color3.fromHex("ebf0f4"), -- list.hoverBackground
    HoverChange = 0.1 -- Slightly more pronounced hover effect
}