return {
    Accent = Color3.fromHex("#0349b4"), -- focusBorder

    AcrylicMain = Color3.fromHex("#ffffff"), -- sideBar.background
    AcrylicBorder = Color3.fromHex("#20252c"), -- titleBar.border
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#ffffff"), Color3.fromHex("#ffffff")), -- sideBar.background
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromHex("#20252c"), -- titleBar.border
    Tab = Color3.fromHex("#0e1116"), -- tab.activeForeground

    Element = Color3.fromHex("#ffffff"), -- input.background
    ElementBorder = Color3.fromHex("#20252c"),  -- input.border
    InElementBorder = Color3.fromHex("#0349b4"), -- focusBorder
    ElementTransparency = 0,

    ToggleSlider = Color3.fromHex("#0349b4"), -- focusBorder
    ToggleToggled = Color3.fromHex("#ffffff"), -- input.background

    SliderRail = Color3.fromHex("#0349b4"), -- focusBorder

    DropdownFrame = Color3.fromHex("#ffffff"), -- dropdown.background
    DropdownHolder = Color3.fromHex("#ffffff"), -- dropdown.background
    DropdownBorder = Color3.fromHex("#20252c"), -- dropdown.border
    DropdownOption = Color3.fromHex("#0e1116"),  -- dropdown.foreground

    Keybind = Color3.fromHex("#ffffff"), -- input.background

    Input = Color3.fromHex("#ffffff"), -- input.background
    InputFocused = Color3.fromHex("#ffffff"),  -- input.background
    InputIndicator = Color3.fromHex("#66707b"), -- input.placeholderForeground

    Dialog = Color3.fromHex("#ffffff"), -- Using a light background for dialog
    DialogHolder = Color3.fromHex("#ffffff"), -- Using a light background for dialog holder
    DialogHolderLine = Color3.fromHex("#20252c"), -- Using a subtle line color
    DialogButton = Color3.fromHex("#ffffff"), -- input.background
    DialogButtonBorder = Color3.fromHex("#20252c"), -- dropdown.border
    DialogBorder = Color3.fromHex("#20252c"), -- dropdown.border
    DialogInput = Color3.fromHex("#ffffff"), -- input.background
    DialogInputLine = Color3.fromHex("#0349b4"),-- focusBorder

    Text = Color3.fromHex("#0e1116"), -- editor.foreground
    SubText = Color3.fromHex("#66707b"), -- descriptionForeground (or a slightly lighter shade)
    Hover = Color3.fromHex("#e7ecf0"), -- list.hoverBackground
    HoverChange = 0.1 -- Slightly more pronounced hover effect
}