return {
    Accent = Color3.fromHex("#a57a4c"), -- focusBorder

    AcrylicMain = Color3.fromHex("#221a0f"), -- editor.background
    AcrylicBorder = Color3.fromHex("#5e452b"), -- editor.lineHighlightBackground
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#221a0f"), Color3.fromHex("#221a0f")),
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromHex("#51412c"), -- input.background
    Tab = Color3.fromHex("#d3af86"), -- editor.foreground

    Element = Color3.fromHex("#51412c"), -- input.background
    ElementBorder = Color3.fromHex("#5e452b"), -- peekView.border
    InElementBorder = Color3.fromHex("#a57a4c"), -- focusBorder
    ElementTransparency = 0,

    ToggleSlider = Color3.fromHex("#a57a4c"), -- focusBorder
    ToggleToggled = Color3.fromHex("#51412c"), -- input.background

    SliderRail = Color3.fromHex("#a57a4c"), -- focusBorder

    DropdownFrame = Color3.fromHex("#51412c"), -- dropdown.background
    DropdownHolder = Color3.fromHex("#51412c"), -- dropdown.background
    DropdownBorder = Color3.fromHex("#5e452b"), -- peekView.border
    DropdownOption = Color3.fromHex("#d3af86"), -- editor.foreground

    Keybind = Color3.fromHex("#51412c"), -- input.background

    Input = Color3.fromHex("#51412c"), -- input.background
    InputFocused = Color3.fromHex("#51412c"), -- input.background
    InputIndicator = Color3.fromHex("#a57a4c"), -- editorWhitespace.foreground

    Dialog = Color3.fromHex("#362712"), -- menu.background
    DialogHolder = Color3.fromHex("#221a14"), -- peekViewEditor.background
    DialogHolderLine = Color3.fromHex("#5e452b"), -- peekView.border
    DialogButton = Color3.fromHex("#6e583b"), -- button.background
    DialogButtonBorder = Color3.fromHex("#5e452b"), -- peekView.border
    DialogBorder = Color3.fromHex("#5e452b"), -- peekView.border
    DialogInput = Color3.fromHex("#51412c"), -- input.background
    DialogInputLine = Color3.fromHex("#a57a4c"), -- focusBorder

    Text = Color3.fromHex("#d3af86"), -- editor.foreground
    SubText = Color3.fromHex("#a57a4c"), -- comments color
    Hover = Color3.fromHex("#7c5021"), -- list.activeSelectionBackground
    HoverChange = 0.1
}