return {
    Accent = Color3.fromHex("#3655b5"), -- focusBorder

    AcrylicMain = Color3.fromHex("#1e1e1e"), -- editor.background
    AcrylicBorder = Color3.fromHex("#303030"), -- tab.border
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#1e1e1e"), Color3.fromHex("#1e1e1e")),
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromHex("#303030"), -- tab.border
    Tab = Color3.fromHex("#d8d8d8"), -- tab.inactiveForeground

    Element = Color3.fromHex("#525252"), -- dropdown.background
    ElementBorder = Color3.fromHex("#505050"), -- titleBar.activeBackground
    InElementBorder = Color3.fromHex("#3655b5"), -- focusBorder
    ElementTransparency = 0,

    ToggleSlider = Color3.fromHex("#3655b5"), -- focusBorder
    ToggleToggled = Color3.fromHex("#525252"), -- dropdown.background

    SliderRail = Color3.fromHex("#3655b5"), -- focusBorder

    DropdownFrame = Color3.fromHex("#525252"), -- dropdown.background
    DropdownHolder = Color3.fromHex("#525252"), -- dropdown.background
    DropdownBorder = Color3.fromHex("#505050"), -- titleBar.activeBackground
    DropdownOption = Color3.fromHex("#c5c8c6"), -- editor.foreground

    Keybind = Color3.fromHex("#525252"), -- dropdown.background

    Input = Color3.fromHex("#525252"), -- dropdown.background
    InputFocused = Color3.fromHex("#525252"), -- dropdown.background
    InputIndicator = Color3.fromHex("#949494"), -- editorLineNumber.activeForeground

    Dialog = Color3.fromHex("#272727"), -- menu.background
    DialogHolder = Color3.fromHex("#272727"), -- menu.background
    DialogHolderLine = Color3.fromHex("#505050"), -- titleBar.activeBackground
    DialogButton = Color3.fromHex("#565656"), -- button.background
    DialogButtonBorder = Color3.fromHex("#505050"), -- titleBar.activeBackground
    DialogBorder = Color3.fromHex("#505050"), -- titleBar.activeBackground
    DialogInput = Color3.fromHex("#525252"), -- dropdown.background
    DialogInputLine = Color3.fromHex("#3655b5"), -- focusBorder

    Text = Color3.fromHex("#c5c8c6"), -- editor.foreground
    SubText = Color3.fromHex("#9A9B99"), -- comment color from tokenColors
    Hover = Color3.fromHex("#444444"), -- list.hoverBackground
    HoverChange = 0.1
}