return {
    Accent = Color3.fromHex("#528bff"), -- activityBarBadge.background

    AcrylicMain = Color3.fromHex("#16171D"), -- editor.background
    AcrylicBorder = Color3.fromHex("#181A1F"), -- editorGroup.border
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#16171D"), Color3.fromHex("#16171D")),
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromHex("#181A1F"), -- editorGroup.border
    Tab = Color3.fromHex("#f8f8f0"), -- editor.foreground

    Element = Color3.fromHex("#1d1f23"), -- dropdown.background
    ElementBorder = Color3.fromHex("#181A11"), -- dropdown.border
    InElementBorder = Color3.fromHex("#528bff"), -- activityBarBadge.background
    ElementTransparency = 0,

    ToggleSlider = Color3.fromHex("#528bff"), -- activityBarBadge.background
    ToggleToggled = Color3.fromHex("#16171D"), -- editor.background

    SliderRail = Color3.fromHex("#528bff"), -- activityBarBadge.background

    DropdownFrame = Color3.fromHex("#1d1f23"), -- dropdown.background
    DropdownHolder = Color3.fromHex("#21252B"), -- editorGroupHeader.tabsBackground
    DropdownBorder = Color3.fromHex("#181A11"), -- dropdown.border
    DropdownOption = Color3.fromHex("#d7dae0"), -- activityBar.foreground

    Keybind = Color3.fromHex("#1d1f23"), -- input.background

    Input = Color3.fromHex("#1d1f23"), -- input.background
    InputFocused = Color3.fromHex("#1d1f23"), -- input.background
    InputIndicator = Color3.fromHex("#495162"), -- editorLineNumber.foreground

    Dialog = Color3.fromHex("#21252B"), -- editorWidget.background
    DialogHolder = Color3.fromHex("#21252B"), -- notifications.background
    DialogHolderLine = Color3.fromHex("#181A1F"), -- editorGroup.border
    DialogButton = Color3.fromHex("#1d1f23"), -- input.background
    DialogButtonBorder = Color3.fromHex("#181A11"), -- dropdown.border
    DialogBorder = Color3.fromHex("#181A1F"), -- editorHoverWidget.border
    DialogInput = Color3.fromHex("#1d1f23"), -- input.background
    DialogInputLine = Color3.fromHex("#528bff"), -- activityBarBadge.background

    Text = Color3.fromHex("#f8f8f0"), -- editor.foreground
    SubText = Color3.fromHex("#5c6370"), -- Comment color
    Hover = Color3.fromHex("#292d35"), -- list.hoverBackground
    HoverChange = 0.1
}