return {
    Accent = Color3.fromHex("#75715E"), -- focusBorder

    AcrylicMain = Color3.fromHex("#272822"), -- editor.background
    AcrylicBorder = Color3.fromHex("#1e1f1c"), -- titleBar.activeBackground
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#272822"), Color3.fromHex("#272822")),
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromHex("#1e1f1c"), -- titleBar.activeBackground
    Tab = Color3.fromHex("#f8f8f2"), -- editor.foreground

    Element = Color3.fromHex("#414339"), -- dropdown.background
    ElementBorder = Color3.fromHex("#75715E"), -- button.background
    InElementBorder = Color3.fromHex("#75715E"), -- focusBorder
    ElementTransparency = 0,

    ToggleSlider = Color3.fromHex("#75715E"), -- button.background
    ToggleToggled = Color3.fromHex("#272822"), -- editor.background

    SliderRail = Color3.fromHex("#75715E"), -- button.background

    DropdownFrame = Color3.fromHex("#414339"), -- dropdown.background
    DropdownHolder = Color3.fromHex("#1e1f1c"), -- dropdown.listBackground
    DropdownBorder = Color3.fromHex("#75715E"), -- button.background
    DropdownOption = Color3.fromHex("#f8f8f2"), -- list.highlightForeground

    Keybind = Color3.fromHex("#414339"), -- dropdown.background

    Input = Color3.fromHex("#414339"), -- input.background
    InputFocused = Color3.fromHex("#414339"), -- input.background
    InputIndicator = Color3.fromHex("#90908a"), -- editorLineNumber.foreground

    Dialog = Color3.fromHex("#1e1f1c"), -- editorWidget.background
    DialogHolder = Color3.fromHex("#1e1f1c"), -- menu.background
    DialogHolderLine = Color3.fromHex("#414339"), -- panel.border
    DialogButton = Color3.fromHex("#414339"), -- dropdown.background
    DialogButtonBorder = Color3.fromHex("#75715E"), -- button.background
    DialogBorder = Color3.fromHex("#75715E"), -- editorHoverWidget.border
    DialogInput = Color3.fromHex("#414339"), -- input.background
    DialogInputLine = Color3.fromHex("#75715E"), -- focusBorder

    Text = Color3.fromHex("#f8f8f2"), -- editor.foreground
    SubText = Color3.fromHex("#88846f"), -- Comment color
    Hover = Color3.fromHex("#3e3d32"), -- list.hoverBackground
    HoverChange = 0.1
}