return {
    Accent = Color3.fromHex("#9769dc"), -- focusBorder

    AcrylicMain = Color3.fromHex("#F5F5F5"), -- editor.background
    AcrylicBorder = Color3.fromHex("#c4b7d7"), -- titleBar.activeBackground
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#F5F5F5"), Color3.fromHex("#F5F5F5")),
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromHex("#c4b7d7"), -- titleBar.activeBackground
    Tab = Color3.fromHex("#705697"), -- activityBar.foreground

    Element = Color3.fromHex("#F2F2F2"), -- sideBar.background
    ElementBorder = Color3.fromHex("#adafb7"), -- inputOption.activeBorder
    InElementBorder = Color3.fromHex("#9769dc"), -- focusBorder
    ElementTransparency = 0,

    ToggleSlider = Color3.fromHex("#705697"), -- activityBarBadge.background
    ToggleToggled = Color3.fromHex("#F5F5F5"), -- editor.background

    SliderRail = Color3.fromHex("#705697"), -- activityBarBadge.background

    DropdownFrame = Color3.fromHex("#F5F5F5"), -- dropdown.background
    DropdownHolder = Color3.fromHex("#F5F5F5"), -- dropdown.background
    DropdownBorder = Color3.fromHex("#adafb7"), -- inputOption.activeBorder
    DropdownOption = Color3.fromHex("#333333"), -- Default text color

    Keybind = Color3.fromHex("#F5F5F5"), -- editor.background

    Input = Color3.fromHex("#F5F5F5"), -- editor.background
    InputFocused = Color3.fromHex("#F5F5F5"), -- editor.background
    InputIndicator = Color3.fromHex("#AAAAAA"), -- editorWhitespace.foreground

    Dialog = Color3.fromHex("#F2F8FC"), -- peekViewEditor.background
    DialogHolder = Color3.fromHex("#F2F8FC"), -- peekViewResult.background
    DialogHolderLine = Color3.fromHex("#705697"), -- peekView.border
    DialogButton = Color3.fromHex("#F5F5F5"), -- editor.background
    DialogButtonBorder = Color3.fromHex("#adafb7"), -- inputOption.activeBorder
    DialogBorder = Color3.fromHex("#705697"), -- peekView.border
    DialogInput = Color3.fromHex("#F5F5F5"), -- editor.background
    DialogInputLine = Color3.fromHex("#9769dc"), -- focusBorder

    Text = Color3.fromHex("#333333"), -- Default foreground
    SubText = Color3.fromHex("#6D705B"), -- editorLineNumber.foreground
    Hover = Color3.fromHex("#e0e0e0"), -- list.hoverBackground
    HoverChange = 0.1
}