return {
    Accent = Color3.fromHex("#2AA198"), -- String color as accent

    AcrylicMain = Color3.fromHex("#002B36"), -- editor.background
    AcrylicBorder = Color3.fromHex("#073642"), -- editor.lineHighlightBackground
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#002B36"), Color3.fromHex("#002B36")),
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromHex("#2AA198"), -- focusBorder
    Tab = Color3.fromHex("#839496"), -- editor.foreground

    Element = Color3.fromHex("#003847"), -- input.background
    ElementBorder = Color3.fromHex("#2AA198"), -- focusBorder
    InElementBorder = Color3.fromHex("#2AA198"), -- String color
    ElementTransparency = 0,

    ToggleSlider = Color3.fromHex("#2AA198"), -- String color
    ToggleToggled = Color3.fromHex("#002B36"), -- editor.background

    SliderRail = Color3.fromHex("#2AA198"), -- String color

    DropdownFrame = Color3.fromHex("#00212B"), -- dropdown.background
    DropdownHolder = Color3.fromHex("#00212B"), -- dropdown.background
    DropdownBorder = Color3.fromHex("#2AA198"), -- dropdown.border
    DropdownOption = Color3.fromHex("#839496"), -- foreground

    Keybind = Color3.fromHex("#003847"), -- input.background

    Input = Color3.fromHex("#003847"), -- input.background
    InputFocused = Color3.fromHex("#003847"), -- input.background
    InputIndicator = Color3.fromHex("#93A1A1"), -- input.placeholderForeground

    Dialog = Color3.fromHex("#00212B"), -- editorWidget.background
    DialogHolder = Color3.fromHex("#002B36"), -- editor.background
    DialogHolderLine = Color3.fromHex("#073642"), -- editor.lineHighlightBackground
    DialogButton = Color3.fromHex("#003847"), -- input.background
    DialogButtonBorder = Color3.fromHex("#2AA198"), -- focusBorder
    DialogBorder = Color3.fromHex("#2AA198"), -- focusBorder
    DialogInput = Color3.fromHex("#003847"), -- input.background
    DialogInputLine = Color3.fromHex("#2AA198"), -- String color

    Text = Color3.fromHex("#839496"), -- editor.foreground
    SubText = Color3.fromHex("#586E75"), -- Comment color
    Hover = Color3.fromHex("#004454"), -- list.hoverBackground
    HoverChange = 0.1
}