return {
    Accent = Color3.fromHex("#b58900"), -- Using the extension button color as accent

    AcrylicMain = Color3.fromHex("#FDF6E3"), -- editor.background
    AcrylicBorder = Color3.fromHex("#DDD6C1"), -- editorGroup.border
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#FDF6E3"), Color3.fromHex("#FDF6E3")),
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromHex("#DDD6C1"), -- editorGroup.border
    Tab = Color3.fromHex("#657B83"), -- editor.foreground

    Element = Color3.fromHex("#EEE8D5"), -- dropdown.background
    ElementBorder = Color3.fromHex("#D3AF86"), -- dropdown.border
    InElementBorder = Color3.fromHex("#b49471"), -- focusBorder
    ElementTransparency = 0,

    ToggleSlider = Color3.fromHex("#b58900"), -- extensionButton.prominentBackground
    ToggleToggled = Color3.fromHex("#FDF6E3"), -- editor.background

    SliderRail = Color3.fromHex("#b58900"), -- extensionButton.prominentBackground

    DropdownFrame = Color3.fromHex("#EEE8D5"), -- dropdown.background
    DropdownHolder = Color3.fromHex("#EEE8D5"), -- dropdown.background
    DropdownBorder = Color3.fromHex("#D3AF86"), -- dropdown.border
    DropdownOption = Color3.fromHex("#657B83"), -- editor.foreground

    Keybind = Color3.fromHex("#DDD6C1"), -- input.background

    Input = Color3.fromHex("#DDD6C1"), -- input.background
    InputFocused = Color3.fromHex("#DDD6C1"), -- input.background
    InputIndicator = Color3.fromHex("#586E75"), -- input.placeholderForeground

    Dialog = Color3.fromHex("#EEE8D5"), -- dropdown.background
    DialogHolder = Color3.fromHex("#EEE8D5"), -- sideBar.background
    DialogHolderLine = Color3.fromHex("#DDD6C1"), -- editorGroup.border
    DialogButton = Color3.fromHex("#AC9D57"), -- button.background
    DialogButtonBorder = Color3.fromHex("#D3AF86"), -- dropdown.border
    DialogBorder = Color3.fromHex("#DDD6C1"), -- editorGroup.border
    DialogInput = Color3.fromHex("#DDD6C1"), -- input.background
    DialogInputLine = Color3.fromHex("#b58900"), -- extensionButton.prominentBackground

    Text = Color3.fromHex("#657B83"), -- editor.foreground
    SubText = Color3.fromHex("#93A1A1"), -- Comment color from tokenColors
    Hover = Color3.fromHex("#DFCA88"), -- list.activeSelectionBackground
    HoverChange = 0.1
}