return {
    Accent = Color3.fromHex("#bbdaff"), -- focusBorder

    AcrylicMain = Color3.fromHex("#002451"), -- editor.background
    AcrylicBorder = Color3.fromHex("#404f7d"), -- editorGroup.border
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#002451"), Color3.fromHex("#002451")),
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromHex("#404f7d"), -- editorGroup.border
    Tab = Color3.fromHex("#ffffff"), -- editor.foreground

    Element = Color3.fromHex("#001733"), -- input.background
    ElementBorder = Color3.fromHex("#404f7d"), -- editorGroup.border
    InElementBorder = Color3.fromHex("#bbdaff"), -- focusBorder
    ElementTransparency = 0,

    ToggleSlider = Color3.fromHex("#bbdaff"), -- focusBorder
    ToggleToggled = Color3.fromHex("#001733"), -- input.background

    SliderRail = Color3.fromHex("#bbdaff"), -- focusBorder

    DropdownFrame = Color3.fromHex("#001733"), -- dropdown.background
    DropdownHolder = Color3.fromHex("#001733"), -- dropdown.background
    DropdownBorder = Color3.fromHex("#404f7d"), -- editorGroup.border
    DropdownOption = Color3.fromHex("#ffffff"), -- editor.foreground

    Keybind = Color3.fromHex("#001733"), -- input.background

    Input = Color3.fromHex("#001733"), -- input.background
    InputFocused = Color3.fromHex("#001733"), -- input.background
    InputIndicator = Color3.fromHex("#404f7d"), -- editorWhitespace.foreground

    Dialog = Color3.fromHex("#001c40"), -- editorWidget.background
    DialogHolder = Color3.fromHex("#001c40"), -- editorWidget.background
    DialogHolderLine = Color3.fromHex("#404f7d"), -- editorGroup.border
    DialogButton = Color3.fromHex("#001733"), -- input.background
    DialogButtonBorder = Color3.fromHex("#404f7d"), -- editorGroup.border
    DialogBorder = Color3.fromHex("#ffffff"), -- editorHoverWidget.border
    DialogInput = Color3.fromHex("#001733"), -- input.background
    DialogInputLine = Color3.fromHex("#bbdaff"), -- focusBorder

    Text = Color3.fromHex("#ffffff"), -- editor.foreground
    SubText = Color3.fromHex("#7285B7"), -- Comment color from tokenColors
    Hover = Color3.fromHex("#ffffff"), -- list.hoverBackground
    HoverChange = 0.1
}