return {
    Accent = Color3.fromRGB(97, 161, 107),

    AcrylicMain = Color3.fromRGB(252, 245, 228),
    AcrylicBorder = Color3.fromRGB(189, 189, 189),
    AcrylicGradient = ColorSequence.new(Color3.fromRGB(252, 245, 228), Color3.fromRGB(228, 220, 200)),
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromRGB(189, 189, 189),
    Tab = Color3.fromRGB(109, 180, 120),

    Element = Color3.fromRGB(255, 255, 255),
    ElementBorder = Color3.fromRGB(200, 200, 200),
    InElementBorder = Color3.fromRGB(191, 191, 193),
    ElementTransparency = 1,

    ToggleSlider = Color3.fromRGB(97, 161, 107),
    ToggleToggled = Color3.fromRGB(255, 255, 255),

    SliderRail = Color3.fromRGB(230, 230, 230),

    DropdownFrame = Color3.fromRGB(217, 218, 220),
    DropdownHolder = Color3.fromRGB(226, 220, 205),
    DropdownBorder = Color3.fromRGB(185, 182, 172),
    DropdownOption = Color3.fromRGB(27, 129, 229),

    Keybind = Color3.fromRGB(233, 227, 211),

    Input = Color3.fromRGB(255, 255, 255),
    InputFocused = Color3.fromRGB(20, 10, 30),
    InputIndicator = Color3.fromRGB(170, 150, 190),

    Dialog = Color3.fromRGB(252, 245, 228),
    DialogHolder = Color3.fromRGB(228, 220, 200),
    DialogHolderLine = Color3.fromRGB(189, 189, 189),
    DialogButton = Color3.fromRGB(242, 243, 245),
    DialogButtonBorder = Color3.fromRGB(213, 213, 215),
    DialogBorder = Color3.fromRGB(189, 189, 189),
    DialogInput = Color3.fromRGB(252, 245, 228),
    DialogInputLine = Color3.fromRGB(190, 160, 180),

    Text = Color3.fromRGB(104, 104, 104),
    SubText = Color3.fromRGB(170, 170, 170),
    Hover = Color3.fromRGB(149, 149, 149),
    HoverChange = 0.04
}