return {
    Accent = Color3.fromHex("#48b258"),

    AcrylicMain = Color3.fromHex("#1e1e1e"),
    AcrylicBorder = Color3.fromHex("#444444"),
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#1e1e1e"), Color3.fromHex("#1e1e1e")),
    AcrylicNoise = 0.92,

    TitleBarLine = Color3.fromHex("#444444"),
    Tab = Color3.fromHex("#dddddd"),

    Element = Color3.fromHex("#242424"),
    ElementBorder = Color3.fromHex("#404040"),
    InElementBorder = Color3.fromHex("#48b258"),
    ElementTransparency = 0,

    ToggleSlider = Color3.fromHex("#48b258"),
    ToggleToggled = Color3.fromHex("#1e1e1e"),

    SliderRail = Color3.fromHex("#48b258"),

    DropdownFrame = Color3.fromHex("#242424"),
    DropdownHolder = Color3.fromHex("#242424"),
    DropdownBorder = Color3.fromHex("#404040"),
    DropdownOption = Color3.fromHex("#dddddd"),

    Keybind = Color3.fromHex("#242424"),

    Input = Color3.fromHex("#242424"),
    InputFocused = Color3.fromHex("#242424"),
    InputIndicator = Color3.fromHex("#808080"),

    Dialog = Color3.fromHex("#242424"),
    DialogHolder = Color3.fromHex("#1e1e1e"),
    DialogHolderLine = Color3.fromHex("#404040"),
    DialogButton = Color3.fromHex("#242424"),
    DialogButtonBorder = Color3.fromHex("#404040"),
    DialogBorder = Color3.fromHex("#444444"),
    DialogInput = Color3.fromHex("#242424"),
    DialogInputLine = Color3.fromHex("#48b258"),

    Text = Color3.fromHex("#dddddd"),
    SubText = Color3.fromHex("#808080"),
    Hover = Color3.fromHex("#2A2D2E"),
    HoverChange = 0.05
}