return {
    Accent = Color3.fromHex("#165fb3"),

    AcrylicMain = Color3.fromHex("#191c28"),
    AcrylicBorder = Color3.fromHex("#191c28"),
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#191c28"), Color3.fromHex("#191c28")),
    AcrylicNoise = 0.92,

    TitleBarLine = Color3.fromHex("#191c28"),
    Tab = Color3.fromHex("#d3d0c8"),

    Element = Color3.fromHex("#191c28"),
    ElementBorder = Color3.fromHex("#191c28"),
    InElementBorder = Color3.fromHex("#165fb3"),
    ElementTransparency = 0,

    ToggleSlider = Color3.fromHex("#165fb3"),
    ToggleToggled = Color3.fromHex("#191c28"),

    SliderRail = Color3.fromHex("#165fb3"),

    DropdownFrame = Color3.fromHex("#191c28"),
    DropdownHolder = Color3.fromHex("#191c28"),
    DropdownBorder = Color3.fromHex("#191c28"),
    DropdownOption = Color3.fromHex("#d3d0c8"),

    Keybind = Color3.fromHex("#191c28"),

    Input = Color3.fromHex("#191c28"),
    InputFocused = Color3.fromHex("#191c28"),
    InputIndicator = Color3.fromHex("#747369"),

    Dialog = Color3.fromHex("#191c28"),
    DialogHolder = Color3.fromHex("#191c28"),
    DialogHolderLine = Color3.fromHex("#191c28"),
    DialogButton = Color3.fromHex("#191c28"),
    DialogButtonBorder = Color3.fromHex("#191c28"),
    DialogBorder = Color3.fromHex("#191c28"),
    DialogInput = Color3.fromHex("#191c28"),
    DialogInputLine = Color3.fromHex("#165fb3"),

    Text = Color3.fromHex("#d3d0c8"),
    SubText = Color3.fromHex("#747369"),
    Hover = Color3.fromHex("#464870"),
    HoverChange = 0.05
}