return {
    Accent = Color3.fromHex("#1591ff"),

    AcrylicMain = Color3.fromHex("#202432"),
    AcrylicBorder = Color3.fromHex("#191c28"),
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#202432"), Color3.fromHex("#202432")),
    AcrylicNoise = 0.92,

    TitleBarLine = Color3.fromHex("#191c28"),
    Tab = Color3.fromHex("#d3d0c8"),

    Element = Color3.fromHex("#202432"),
    ElementBorder = Color3.fromHex("#0d2c5a"),
    InElementBorder = Color3.fromHex("#1591ff"),
    ElementTransparency = 0.85,

    ToggleSlider = Color3.fromHex("#1591ff"),
    ToggleToggled = Color3.fromHex("#202432"),

    SliderRail = Color3.fromHex("#1591ff"),

    DropdownFrame = Color3.fromHex("#202432"),
    DropdownHolder = Color3.fromHex("#1e2228"),
    DropdownBorder = Color3.fromHex("#0d2c5a"),
    DropdownOption = Color3.fromHex("#d3d0c8"),

    Keybind = Color3.fromHex("#202432"),

    Input = Color3.fromHex("#202432"),
    InputFocused = Color3.fromHex("#202432"),
    InputIndicator = Color3.fromHex("#747369"),

    Dialog = Color3.fromHex("#252f46"),
    DialogHolder = Color3.fromHex("#1c1f2b"),
    DialogHolderLine = Color3.fromHex("#1b375c"),
    DialogButton = Color3.fromHex("#202432"),
    DialogButtonBorder = Color3.fromHex("#0d2c5a"),
    DialogBorder = Color3.fromHex("#1591ff"),
    DialogInput = Color3.fromHex("#202432"),
    DialogInputLine = Color3.fromHex("#1591ff"),

    Text = Color3.fromHex("#d3d0c8"),
    SubText = Color3.fromHex("#747369"),
    Hover = Color3.fromHex("#1b375c"),
    HoverChange = 0.05
}