return {
    Accent = Color3.fromHex("#e32b00"),

    AcrylicMain = Color3.fromHex("#130c0f"),
    AcrylicBorder = Color3.fromHex("#28191d"),
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#130c0f"), Color3.fromHex("#130c0f")),
    AcrylicNoise = 0.92,

    TitleBarLine = Color3.fromHex("#28191d"),
    Tab = Color3.fromHex("#d3d0c8"),

    Element = Color3.fromHex("#321f27"),
    ElementBorder = Color3.fromHex("#5a0d29"),
    InElementBorder = Color3.fromHex("#e32b00"),
    ElementTransparency = 0.85,

    ToggleSlider = Color3.fromHex("#e32b00"),
    ToggleToggled = Color3.fromHex("#130c0f"),

    SliderRail = Color3.fromHex("#e32b00"),

    DropdownFrame = Color3.fromHex("#321f27"),
    DropdownHolder = Color3.fromHex("#271e22"),
    DropdownBorder = Color3.fromHex("#5a0d29"),
    DropdownOption = Color3.fromHex("#d3d0c8"),

    Keybind = Color3.fromHex("#321f27"),

    Input = Color3.fromHex("#321f27"),
    InputFocused = Color3.fromHex("#321f27"),
    InputIndicator = Color3.fromHex("#747369"),

    Dialog = Color3.fromHex("#462531"),
    DialogHolder = Color3.fromHex("#3a1223"),
    DialogHolderLine = Color3.fromHex("#5c1b33"),
    DialogButton = Color3.fromHex("#321f27"),
    DialogButtonBorder = Color3.fromHex("#5a0d29"),
    DialogBorder = Color3.fromHex("#ff4f15"),
    DialogInput = Color3.fromHex("#321f27"),
    DialogInputLine = Color3.fromHex("#e32b00"),

    Text = Color3.fromHex("#d3d0c8"),
    SubText = Color3.fromHex("#747369"),
    Hover = Color3.fromHex("#5c1b33"),
    HoverChange = 0.05
}