return {
    Accent = Color3.fromHex("#7b36e2"),

    AcrylicMain = Color3.fromHex("#110e1a"),
    AcrylicBorder = Color3.fromHex("#444444"),
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#110e1a"), Color3.fromHex("#110e1a")),
    AcrylicNoise = 0.92,

    TitleBarLine = Color3.fromHex("#444444"),
    Tab = Color3.fromHex("#CCCCCC"),

    Element = Color3.fromHex("#2D2D2D"),
    ElementBorder = Color3.fromHex("#404040"),
    InElementBorder = Color3.fromHex("#7b36e2"),
    ElementTransparency = 0.85,

    ToggleSlider = Color3.fromHex("#7b36e2"),
    ToggleToggled = Color3.fromHex("#110e1a"),

    SliderRail = Color3.fromHex("#7b36e2"),

    DropdownFrame = Color3.fromHex("#2D2D2D"),
    DropdownHolder = Color3.fromHex("#252526"),
    DropdownBorder = Color3.fromHex("#404040"),
    DropdownOption = Color3.fromHex("#a497b5"),

    Keybind = Color3.fromHex("#2D2D2D"),

    Input = Color3.fromHex("#3C3C3C"),
    InputFocused = Color3.fromHex("#3C3C3C"),
    InputIndicator = Color3.fromHex("#808080"),

    Dialog = Color3.fromHex("#2a1c3e"),
    DialogHolder = Color3.fromHex("#150E33"),
    DialogHolderLine = Color3.fromHex("#100422"),
    DialogButton = Color3.fromHex("#2D2D2D"),
    DialogButtonBorder = Color3.fromHex("#404040"),
    DialogBorder = Color3.fromHex("#444444"),
    DialogInput = Color3.fromHex("#3C3C3C"),
    DialogInputLine = Color3.fromHex("#7b36e2"),

    Text = Color3.fromHex("#a497b5"),
    SubText = Color3.fromHex("#60576f"),
    Hover = Color3.fromHex("#2A2D2E"),
    HoverChange = 0.05
}