return {
    Accent = Color3.fromHex("#165fb3"),

    AcrylicMain = Color3.fromHex("#21252b"),
    AcrylicBorder = Color3.fromHex("#383838"),
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#21252b"), Color3.fromHex("#21252b")),
    AcrylicNoise = 0.92,

    TitleBarLine = Color3.fromHex("#383838"),
    Tab = Color3.fromHex("#d3d0c8"),

    Element = Color3.fromHex("#2d333c"),
    ElementBorder = Color3.fromHex("#383838"),
    InElementBorder = Color3.fromHex("#165fb3"),
    ElementTransparency = 0.85,

    ToggleSlider = Color3.fromHex("#165fb3"),
    ToggleToggled = Color3.fromHex("#21252b"),

    SliderRail = Color3.fromHex("#165fb3"),

    DropdownFrame = Color3.fromHex("#2d333c"),
    DropdownHolder = Color3.fromHex("#1e2228"),
    DropdownBorder = Color3.fromHex("#383838"),
    DropdownOption = Color3.fromHex("#d3d0c8"),

    Keybind = Color3.fromHex("#2d333c"),

    Input = Color3.fromHex("#2d333c"),
    InputFocused = Color3.fromHex("#2d333c"),
    InputIndicator = Color3.fromHex("#747369"),

    Dialog = Color3.fromHex("#21252b"),
    DialogHolder = Color3.fromHex("#1E2228"),
    DialogHolderLine = Color3.fromHex("#383838"),
    DialogButton = Color3.fromHex("#2d333c"),
    DialogButtonBorder = Color3.fromHex("#383838"),
    DialogBorder = Color3.fromHex("#383838"),
    DialogInput = Color3.fromHex("#2d333c"),
    DialogInputLine = Color3.fromHex("#165fb3"),

    Text = Color3.fromHex("#d3d0c8"),
    SubText = Color3.fromHex("#747369"),
    Hover = Color3.fromHex("#383838"),
    HoverChange = 0.05
}