return {
    Accent = Color3.fromHex("#0f96ff"),

    AcrylicMain = Color3.fromHex("#ffffff"),
    AcrylicBorder = Color3.fromHex("#d4d4d4"),
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#ffffff"), Color3.fromHex("#ffffff")),
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromHex("#d4d4d4"),
    Tab = Color3.fromHex("#8e8e8e"),

    Element = Color3.fromHex("#f3f3f3"),
    ElementBorder = Color3.fromHex("#cecece"),
    InElementBorder = Color3.fromHex("#0f96ff"),
    ElementTransparency = 0,

    ToggleSlider = Color3.fromHex("#0f96ff"),
    ToggleToggled = Color3.fromHex("#ffffff"),

    SliderRail = Color3.fromHex("#0f96ff"),

    DropdownFrame = Color3.fromHex("#ffffff"),
    DropdownHolder = Color3.fromHex("#ffffff"),
    DropdownBorder = Color3.fromHex("#cecece"),
    DropdownOption = Color3.fromHex("#57606c"),

    Keybind = Color3.fromHex("#ffffff"),

    Input = Color3.fromHex("#ffffff"),
    InputFocused = Color3.fromHex("#ffffff"),
    InputIndicator = Color3.fromHex("#767676"),

    Dialog = Color3.fromHex("#f3f3f3"),
    DialogHolder = Color3.fromHex("#ffffff"),
    DialogHolderLine = Color3.fromHex("#d4d4d4"),
    DialogButton = Color3.fromHex("#f3f3f3"),
    DialogButtonBorder = Color3.fromHex("#cecece"),
    DialogBorder = Color3.fromHex("#d4d4d4"),
    DialogInput = Color3.fromHex("#ffffff"),
    DialogInputLine = Color3.fromHex("#0f96ff"),

    Text = Color3.fromHex("#57606c"),
    SubText = Color3.fromHex("#6f6f6f"),
    Hover = Color3.fromHex("#e8e8e8"),
    HoverChange = 0.1
}