return {
    Accent = Color3.fromHex("#007ACC"), -- activityBarBadge.background

    AcrylicMain = Color3.fromHex("#1E1E1E"), -- editor.background
    AcrylicBorder = Color3.fromHex("#303031"), -- widget.border
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#1E1E1E"), Color3.fromHex("#1E1E1E")),
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromHex("#303031"), -- widget.border
    Tab = Color3.fromHex("#ffffff"), -- tab.selectedForeground

    Element = Color3.fromHex("#222222"), -- tab.selectedBackground
    ElementBorder = Color3.fromHex("#6B6B6B"), -- checkbox.border
    InElementBorder = Color3.fromHex("#007ACC"), -- activityBarBadge.background
    ElementTransparency = 0,

    ToggleSlider = Color3.fromHex("#007ACC"), -- activityBarBadge.background
    ToggleToggled = Color3.fromHex("#222222"), -- tab.selectedBackground

    SliderRail = Color3.fromHex("#404040"), -- editorIndentGuide.background1

    DropdownFrame = Color3.fromHex("#252526"), -- menu.background
    DropdownHolder = Color3.fromHex("#252526"), -- menu.background
    DropdownBorder = Color3.fromHex("#454545"), -- menu.border
    DropdownOption = Color3.fromHex("#CCCCCC"), -- menu.foreground

    Keybind = Color3.fromHex("#222222"), -- tab.selectedBackground

    Input = Color3.fromHex("#222222"), -- tab.selectedBackground
    InputFocused = Color3.fromHex("#222222"), -- tab.selectedBackground
    InputIndicator = Color3.fromHex("#A6A6A6"), -- input.placeholderForeground

    Dialog = Color3.fromHex("#252526"), -- menu.background
    DialogHolder = Color3.fromHex("#252526"), -- menu.background
    DialogHolderLine = Color3.fromHex("#454545"), -- menu.separatorBackground
    DialogButton = Color3.fromHex("#222222"), -- tab.selectedBackground
    DialogButtonBorder = Color3.fromHex("#454545"), -- menu.border
    DialogBorder = Color3.fromHex("#454545"), -- menu.border
    DialogInput = Color3.fromHex("#222222"), -- tab.selectedBackground
    DialogInputLine = Color3.fromHex("#007ACC"), -- activityBarBadge.background

    Text = Color3.fromHex("#D4D4D4"), -- editor.foreground
    SubText = Color3.fromHex("#BBBBBB"), -- sideBarTitle.foreground
    Hover = Color3.fromHex("#383B3D"), -- list.dropBackground
    HoverChange = 0.1
}