return {
    Accent = Color3.fromRGB(0, 107, 189),

    AcrylicMain = Color3.fromRGB(255, 255, 255),
    AcrylicBorder = Color3.fromRGB(15, 74, 133),
    AcrylicGradient = ColorSequence.new(Color3.fromRGB(255, 255, 255), Color3.fromRGB(255, 255, 255)),
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromRGB(15, 74, 133),
    Tab = Color3.fromRGB(0, 107, 189),

    Element = Color3.fromRGB(255, 255, 255),
    ElementBorder = Color3.fromRGB(15, 74, 133),
    InElementBorder = Color3.fromRGB(15, 74, 133),
    ElementTransparency = 1,

    ToggleSlider = Color3.fromRGB(15, 74, 133),
    ToggleToggled = Color3.fromRGB(0, 0, 0),

    SliderRail = Color3.fromRGB(15, 74, 133),

    DropdownFrame = Color3.fromRGB(255, 255, 255),
    DropdownHolder = Color3.fromRGB(255, 255, 255),
    DropdownBorder = Color3.fromRGB(15, 74, 133),
    DropdownOption = Color3.fromRGB(0, 107, 189),

    Keybind = Color3.fromRGB(255, 255, 255),

    Input = Color3.fromRGB(255, 255, 255),
    InputFocused = Color3.fromRGB(255, 255, 255),
    InputIndicator = Color3.fromRGB(170, 150, 190),

    Dialog = Color3.fromRGB(255, 255, 255),
    DialogHolder = Color3.fromRGB(255, 255, 255),
    DialogHolderLine = Color3.fromRGB(0, 107, 189),
    DialogButton = Color3.fromRGB(255, 255, 255),
    DialogButtonBorder = Color3.fromRGB(0, 107, 189),
    DialogBorder = Color3.fromRGB(15, 74, 133),
    DialogInput = Color3.fromRGB(255, 255, 255),
    DialogInputLine = Color3.fromRGB(15, 74, 133),

    Text = Color3.fromRGB(41, 41, 41),
    SubText = Color3.fromRGB(56, 56, 56),
    Hover = Color3.fromRGB(255, 120, 170),
    HoverChange = 0.04
}