return {
    Accent = Color3.fromRGB(111, 195, 223),

    AcrylicMain = Color3.fromRGB(0, 0, 0),
    AcrylicBorder = Color3.fromRGB(111, 195, 223),
    AcrylicGradient = ColorSequence.new(Color3.fromRGB(0, 0, 0), Color3.fromRGB(0, 0, 0)),
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromRGB(111, 195, 223),
    Tab = Color3.fromRGB(243, 133, 24),

    Element = Color3.fromRGB(0, 0, 0),
    ElementBorder = Color3.fromRGB(243, 133, 24),
    InElementBorder = Color3.fromRGB(111, 195, 223),
    ElementTransparency = 0,

    ToggleSlider = Color3.fromRGB(111, 195, 223),
    ToggleToggled = Color3.fromRGB(0, 0, 0),

    SliderRail = Color3.fromRGB(111, 195, 223),

    DropdownFrame = Color3.fromRGB(0, 0, 0),
    DropdownHolder = Color3.fromRGB(0, 0, 0),
    DropdownBorder = Color3.fromRGB(111, 195, 223),
    DropdownOption = Color3.fromRGB(243, 133, 24),

    Keybind = Color3.fromRGB(0, 0, 0),

    Input = Color3.fromRGB(0, 0, 0),
    InputFocused = Color3.fromRGB(0, 0, 0),
    InputIndicator = Color3.fromRGB(170, 150, 190),

    Dialog = Color3.fromRGB(11, 18, 28),
    DialogHolder = Color3.fromRGB(11, 18, 28),
    DialogHolderLine = Color3.fromRGB(255, 255, 255),
    DialogButton = Color3.fromRGB(0, 0, 0),
    DialogButtonBorder = Color3.fromRGB(111, 195, 223),
    DialogBorder = Color3.fromRGB(111, 195, 223),
    DialogInput = Color3.fromRGB(0, 0, 0),
    DialogInputLine = Color3.fromRGB(111, 195, 223),

    Text = Color3.fromRGB(255, 255, 255),
    SubText = Color3.fromRGB(220, 220, 220),
    Hover = Color3.fromRGB(255, 120, 170),
    HoverChange = 0.04
}