return {
    Accent = Color3.fromHex("#005FB8"), -- focusBorder

    AcrylicMain = Color3.fromHex("#F8F8F8"), -- activityBar.background
    AcrylicBorder = Color3.fromHex("#E5E5E5"), -- activityBar.border
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#F8F8F8"), Color3.fromHex("#F8F8F8")),
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromHex("#E5E5E5"), -- titleBar.border
    Tab = Color3.fromHex("#1F1F1F"), -- activityBar.foreground

    Element = Color3.fromHex("#E5E5E5"), -- button.secondaryBackground
    ElementBorder = Color3.fromHex("#CECECE"), -- button.border
    InElementBorder = Color3.fromHex("#005FB8"), -- focusBorder
    ElementTransparency = 0,

    ToggleSlider = Color3.fromHex("#005FB8"), -- focusBorder
    ToggleToggled = Color3.fromHex("#FFFFFF"), -- editor.background

    SliderRail = Color3.fromHex("#005FB8"), -- focusBorder

    DropdownFrame = Color3.fromHex("#FFFFFF"), -- dropdown.background
    DropdownHolder = Color3.fromHex("#FFFFFF"), -- dropdown.background
    DropdownBorder = Color3.fromHex("#CECECE"), -- dropdown.border
    DropdownOption = Color3.fromHex("#3B3B3B"), -- dropdown.foreground

    Keybind = Color3.fromHex("#FFFFFF"), -- input.background

    Input = Color3.fromHex("#FFFFFF"), -- input.background
    InputFocused = Color3.fromHex("#FFFFFF"), -- input.background
    InputIndicator = Color3.fromHex("#767676"), -- input.placeholderForeground

    Dialog = Color3.fromHex("#F8F8F8"), -- editorWidget.background
    DialogHolder = Color3.fromHex("#FFFFFF"), -- editor.background
    DialogHolderLine = Color3.fromHex("#E5E5E5"), -- panel.border
    DialogButton = Color3.fromHex("#E5E5E5"), -- button.secondaryBackground
    DialogButtonBorder = Color3.fromHex("#CECECE"), -- button.border
    DialogBorder = Color3.fromHex("#E5E5E5"), -- notifications.border
    DialogInput = Color3.fromHex("#FFFFFF"), -- input.background
    DialogInputLine = Color3.fromHex("#005FB8"), -- focusBorder

    Text = Color3.fromHex("#3B3B3B"), -- foreground
    SubText = Color3.fromHex("#616161"), -- activityBar.inactiveForeground
    Hover = Color3.fromHex("#F2F2F2"), -- list.hoverBackground
    HoverChange = 0.1
}