return {
    Accent = Color3.fromHex("#cc3333"), -- badge.background

    AcrylicMain = Color3.fromHex("#580000"), -- activityBar.background
    AcrylicBorder = Color3.fromHex("#ff6666"), -- focusBorder
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#580000"), Color3.fromHex("#580000")),
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromHex("#772222"), -- titleBar.inactiveBackground
    Tab = Color3.fromHex("#F8F8F8"), -- editor.foreground

    Element = Color3.fromHex("#580000"), -- dropdown.background
    ElementBorder = Color3.fromHex("#ff6666"), -- editorGroup.border
    InElementBorder = Color3.fromHex("#cc0000"), -- inputOption.activeBorder
    ElementTransparency = 0,

    ToggleSlider = Color3.fromHex("#cc3333"), -- badge.background
    ToggleToggled = Color3.fromHex("#300000"), -- editorWidget.background

    SliderRail = Color3.fromHex("#cc3333"), -- badge.background

    DropdownFrame = Color3.fromHex("#580000"), -- dropdown.background
    DropdownHolder = Color3.fromHex("#580000"), -- dropdown.background
    DropdownBorder = Color3.fromHex("#220000"), -- editorSuggestWidget.border
    DropdownOption = Color3.fromHex("#F8F8F8"), -- editor.foreground

    Keybind = Color3.fromHex("#580000"), -- dropdown.background

    Input = Color3.fromHex("#580000"), -- input.background
    InputFocused = Color3.fromHex("#580000"), -- input.background
    InputIndicator = Color3.fromHex("#c10000"), -- editorWhitespace.foreground

    Dialog = Color3.fromHex("#300000"), -- editorWidget.background
    DialogHolder = Color3.fromHex("#300000"), -- editorWidget.background
    DialogHolderLine = Color3.fromHex("#ff0000"), -- peekView.border
    DialogButton = Color3.fromHex("#833333"), -- button.background
    DialogButtonBorder = Color3.fromHex("#662222"), -- list.dropBackground
    DialogBorder = Color3.fromHex("#220000"), -- editorSuggestWidget.border
    DialogInput = Color3.fromHex("#580000"), -- input.background
    DialogInputLine = Color3.fromHex("#cc3333"), -- badge.background

    Text = Color3.fromHex("#F8F8F8"), -- editor.foreground
    SubText = Color3.fromHex("#e7c0c0"), -- comment color from tokenColors
    Hover = Color3.fromHex("#800000"), -- list.hoverBackground
    HoverChange = 0.1
}