return {
    Accent = Color3.fromHex("#795E26"), -- Function declarations color

    AcrylicMain = Color3.fromHex("#FFFFFF"), -- editor.background
    AcrylicBorder = Color3.fromHex("#D4D4D4"), -- menu.border
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#FFFFFF"), Color3.fromHex("#FFFFFF")),
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromHex("#D4D4D4"), -- menu.border
    Tab = Color3.fromHex("#000000"), -- editor.foreground

    Element = Color3.fromHex("#F3F3F3"), -- editorSuggestWidget.background
    ElementBorder = Color3.fromHex("#CECECE"), -- searchEditor.textInputBorder
    InElementBorder = Color3.fromHex("#795E26"), -- Function color as accent
    ElementTransparency = 0,

    ToggleSlider = Color3.fromHex("#795E26"), -- Function color as accent
    ToggleToggled = Color3.fromHex("#FFFFFF"), -- editor.background

    SliderRail = Color3.fromHex("#795E26"), -- Function color as accent

    DropdownFrame = Color3.fromHex("#FFFFFF"), -- editor.background
    DropdownHolder = Color3.fromHex("#FFFFFF"), -- editor.background
    DropdownBorder = Color3.fromHex("#CECECE"), -- searchEditor.textInputBorder
    DropdownOption = Color3.fromHex("#001080"), -- Variable color

    Keybind = Color3.fromHex("#FFFFFF"), -- editor.background

    Input = Color3.fromHex("#FFFFFF"), -- editor.background
    InputFocused = Color3.fromHex("#FFFFFF"), -- editor.background
    InputIndicator = Color3.fromHex("#767676"), -- input.placeholderForeground

    Dialog = Color3.fromHex("#F3F3F3"), -- editorSuggestWidget.background
    DialogHolder = Color3.fromHex("#FFFFFF"), -- editor.background
    DialogHolderLine = Color3.fromHex("#D4D4D4"), -- menu.border
    DialogButton = Color3.fromHex("#F3F3F3"), -- editorSuggestWidget.background
    DialogButtonBorder = Color3.fromHex("#CECECE"), -- searchEditor.textInputBorder
    DialogBorder = Color3.fromHex("#D4D4D4"), -- menu.border
    DialogInput = Color3.fromHex("#FFFFFF"), -- editor.background
    DialogInputLine = Color3.fromHex("#795E26"), -- Function color as accent

    Text = Color3.fromHex("#000000"), -- editor.foreground
    SubText = Color3.fromHex("#6F6F6F"), -- sideBarTitle.foreground
    Hover = Color3.fromHex("#E8E8E8"), -- list.hoverBackground
    HoverChange = 0.1
} 