return {
    Accent = Color3.fromHex("#569cd6"), -- Based on keyword color

    AcrylicMain = Color3.fromHex("#000000"), -- editor.background
    AcrylicBorder = Color3.fromHex("#FFFFFF"), -- Based on editor.foreground
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#000000"), Color3.fromHex("#000000")),
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromHex("#FFFFFF"),
    Tab = Color3.fromHex("#FFFFFF"),

    Element = Color3.fromHex("#000000"),
    ElementBorder = Color3.fromHex("#FFFFFF"),
    InElementBorder = Color3.fromHex("#569cd6"),
    ElementTransparency = 0,

    ToggleSlider = Color3.fromHex("#569cd6"),
    ToggleToggled = Color3.fromHex("#000000"),

    SliderRail = Color3.fromHex("#569cd6"),

    DropdownFrame = Color3.fromHex("#000000"),
    DropdownHolder = Color3.fromHex("#000000"),
    DropdownBorder = Color3.fromHex("#FFFFFF"),
    DropdownOption = Color3.fromHex("#FFFFFF"),

    Keybind = Color3.fromHex("#000000"),

    Input = Color3.fromHex("#000000"),
    InputFocused = Color3.fromHex("#000000"),
    InputIndicator = Color3.fromHex("#7c7c7c"), -- Based on editorWhitespace.foreground

    Dialog = Color3.fromHex("#000000"),
    DialogHolder = Color3.fromHex("#000000"),
    DialogHolderLine = Color3.fromHex("#FFFFFF"),
    DialogButton = Color3.fromHex("#000000"),
    DialogButtonBorder = Color3.fromHex("#FFFFFF"),
    DialogBorder = Color3.fromHex("#FFFFFF"),
    DialogInput = Color3.fromHex("#000000"),
    DialogInputLine = Color3.fromHex("#569cd6"),

    Text = Color3.fromHex("#FFFFFF"), -- editor.foreground
    SubText = Color3.fromHex("#9D9D9D"), -- descriptionForeground
    Hover = Color3.fromHex("#383a49"), -- Based on actionBar.toggledBackground
    HoverChange = 0.1
}