return {
    Accent = Color3.fromHex("#0078D4"), -- focusBorder

    AcrylicMain = Color3.fromHex("#181818"), -- activityBar.background
    AcrylicBorder = Color3.fromHex("#2B2B2B"), -- activityBar.border
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#181818"), Color3.fromHex("#181818")), -- activityBar.background
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromHex("#2B2B2B"), -- titleBar.border
    Tab = Color3.fromHex("#FFFFFF"), -- tab.activeForeground

    Element = Color3.fromHex("#313131"), -- button.secondaryBackground
    ElementBorder = Color3.fromHex("#3C3C3C"), -- button.secondaryHoverBackground
    InElementBorder = Color3.fromHex("#0078D4"), -- focusBorder
    ElementTransparency = 0,

    ToggleSlider = Color3.fromHex("#0078D4"), -- focusBorder
    ToggleToggled = Color3.fromHex("#313131"), -- checkbox.background

    SliderRail = Color3.fromHex("#0078D4"), -- focusBorder

    DropdownFrame = Color3.fromHex("#313131"), -- dropdown.background
    DropdownHolder = Color3.fromHex("#313131"), -- dropdown.background
    DropdownBorder = Color3.fromHex("#3C3C3C"), -- dropdown.border
    DropdownOption = Color3.fromHex("#CCCCCC"), -- dropdown.foreground

    Keybind = Color3.fromHex("#313131"), -- input.background

    Input = Color3.fromHex("#313131"), -- input.background
    InputFocused = Color3.fromHex("#313131"), -- input.background
    InputIndicator = Color3.fromHex("#989898"), -- input.placeholderForeground

    Dialog = Color3.fromHex("#202020"), -- editorWidget.background
    DialogHolder = Color3.fromHex("#1F1F1F"), -- editor.background
    DialogHolderLine = Color3.fromHex("#2B2B2B"), -- panel.border
    DialogButton = Color3.fromHex("#313131"), -- button.secondaryBackground
    DialogButtonBorder = Color3.fromHex("#3C3C3C"), -- button.secondaryHoverBackground
    DialogBorder = Color3.fromHex("#2B2B2B"), -- notifications.border
    DialogInput = Color3.fromHex("#313131"), -- input.background
    DialogInputLine = Color3.fromHex("#0078D4"), -- focusBorder

    Text = Color3.fromHex("#CCCCCC"), -- foreground
    SubText = Color3.fromHex("#9D9D9D"), -- descriptionForeground
    Hover = Color3.fromHex("#3C3C3C"), -- button.secondaryHoverBackground
    HoverChange = 0.1
}