return {
    Accent = Color3.fromHex("#e95420"),

    AcrylicMain = Color3.fromHex("#edeef0"),
    AcrylicBorder = Color3.fromHex("#D4D4D4"),
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#edeef0"), Color3.fromHex("#edeef0")),
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromHex("#D4D4D4"),
    Tab = Color3.fromHex("#111111"),

    Element = Color3.fromHex("#FFFFFF"),
    ElementBorder = Color3.fromHex("#CECECE"),
    InElementBorder = Color3.fromHex("#e95420"),
    ElementTransparency = 0,

    ToggleSlider = Color3.fromHex("#e95420"),
    ToggleToggled = Color3.fromHex("#FFFFFF"),

    SliderRail = Color3.fromHex("#e95420"),

    DropdownFrame = Color3.fromHex("#FFFFFF"),
    DropdownHolder = Color3.fromHex("#FFFFFF"),
    DropdownBorder = Color3.fromHex("#CECECE"),
    DropdownOption = Color3.fromHex("#111111"),

    Keybind = Color3.fromHex("#FFFFFF"),

    Input = Color3.fromHex("#FFFFFF"),
    InputFocused = Color3.fromHex("#FFFFFF"),
    InputIndicator = Color3.fromHex("#767676"),

    Dialog = Color3.fromHex("#f6f6f6"),
    DialogHolder = Color3.fromHex("#FFFFFF"),
    DialogHolderLine = Color3.fromHex("#D4D4D4"),
    DialogButton = Color3.fromHex("#f6f6f6"),
    DialogButtonBorder = Color3.fromHex("#CECECE"),
    DialogBorder = Color3.fromHex("#D4D4D4"),
    DialogInput = Color3.fromHex("#FFFFFF"),
    DialogInputLine = Color3.fromHex("#e95420"),

    Text = Color3.fromHex("#111111"),
    SubText = Color3.fromHex("#6F6F6F"),
    Hover = Color3.fromHex("#E8E8E8"),
    HoverChange = 0.1
}