return {
    Accent = Color3.fromHex("#e95420"),

    AcrylicMain = Color3.fromHex("#383838"),
    AcrylicBorder = Color3.fromHex("#444444"),
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#383838"), Color3.fromHex("#383838")),
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromHex("#444444"),
    Tab = Color3.fromHex("#FFFFFF"),

    Element = Color3.fromHex("#484848"),
    ElementBorder = Color3.fromHex("#404040"),
    InElementBorder = Color3.fromHex("#e95420"),
    ElementTransparency = 0,

    ToggleSlider = Color3.fromHex("#e95420"),
    ToggleToggled = Color3.fromHex("#2f2f2f"),

    SliderRail = Color3.fromHex("#e95420"),

    DropdownFrame = Color3.fromHex("#484848"),
    DropdownHolder = Color3.fromHex("#484848"),
    DropdownBorder = Color3.fromHex("#404040"),
    DropdownOption = Color3.fromHex("#FFFFFF"),

    Keybind = Color3.fromHex("#484848"),

    Input = Color3.fromHex("#484848"),
    InputFocused = Color3.fromHex("#484848"),
    InputIndicator = Color3.fromHex("#636e7b"),

    Dialog = Color3.fromHex("#434343"),
    DialogHolder = Color3.fromHex("#2f2f2f"),
    DialogHolderLine = Color3.fromHex("#404040"),
    DialogButton = Color3.fromHex("#484848"),
    DialogButtonBorder = Color3.fromHex("#404040"),
    DialogBorder = Color3.fromHex("#444444"),
    DialogInput = Color3.fromHex("#484848"),
    DialogInputLine = Color3.fromHex("#e95420"),

    Text = Color3.fromHex("#FFFFFF"),
    SubText = Color3.fromHex("#808080"),
    Hover = Color3.fromHex("#575757"),
    HoverChange = 0.1
}